language: android
before_script: ./pre-build.sh && sed -i "s#gradle:2.0.0-rc3#gradle:1.5.0#" build.gradle
jdk: openjdk7
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
script: gradle build connectedCheck -PbuildServer

